### ISSUE TITLE
Is this project still being actively maintained?

### ISSUE THREAD

**Issue by jondmcelroy** [Seldaek/monolog#1149]
Hi @Seldaek ,
I haven't seen any commit activity, PR merging or issue commenting since June 2017. 
Is there a plan to continue maintaining this project? Or maybe a plan to pass off ownership/maintenance?

Thanks

**Comment by Seldaek** [comment]
Yes yes.. I know..

It's not that I don't care, believe me, but it's been hard to find the time. So yes I have received a couple emails from people (👋 @ralphschindler, @lyrixx, @Nyholm) offering to take over some maintenance work and I'd like to do that because clearly I don't scale here. If anyone else is *seriously* interested and ideally not going to do insane things, please do tell.

I have some vacation coming up now so I don't have time right now yet again, but I'll try and gather some thoughts and write up some vision of what I had in mind going forward in the next couple weeks.

**Comment by ralphschindler** [comment]
I am more than happy to start triaging PRs for you and labeling them with reasonings as to what/how/if I think they should be applied.

**Comment by lyrixx** [comment]
As I said it to @Seldaek by mail, I will be honored to help you to maintain this project ;)
I really love logs so it will be a pleasure. I have already some idea to help this project to move forward (like creating a "monolog-contrib" repository to externalize all 3rd party handlers)

**Comment by Korbeil** [comment]
Would like to help too if anything needed ! Prob not as maintainer but could give a hand to him ;)

**Comment by localheinz** [comment]
Happy to help out, too.

**Comment by helhum** [comment]
I would be in as well. Let me know how we can proceed. Maybe start with a conference call/ hangout?

**Comment by stof** [comment]
> (like creating a "monolog-contrib" repository to externalize all 3rd party handlers

I'd rather let each one create their own package with their third-party handler, that they would maintain, and which could have composer requirements, rather than having a huge `monolog-contrib` package full of unmaintained handlers (because nobody would be responsible for the maintenance of this package) with requirements to be managed by users themselves (because they cannot be requirements if only one handler uses them)

**Comment by Seldaek** [comment]
Alright so I went through all open issues/PRs, brought it all down to a manageable level again.

Now that I have an overview of the project again, here are the items where help would be greatly appreciated in the short term:

- [ ] Bringing the [1.x milestone](https://github.com/Seldaek/monolog/milestone/5) to completion so that 1.24.0 can be released. #1076 needs work done IMO, https://github.com/Seldaek/monolog/pull/997 needs @lyrixx to rename things unless someone has a good point against my last comment there, and https://github.com/Seldaek/monolog/pull/1117 needs review.
- [ ] 2.0 is the next big task, and I'd really love to get an alpha/beta out soon but there are still some items that need to be cleared up first:
  - [ ] See items on top of https://github.com/Seldaek/monolog/issues/197 - the first one needs a bigger discussion whether this is necessary at all. I would tend to say maybe we leave it as is to avoid major breakage everywhere, but happy to have a discussion (maybe in a separate issue). Second one (add scalar hints and return type hints where relevant) would be good to have people helping out there going through all handlers. I did the rest of the code a while back so I think it's fine but we have to see what could benefit from the recent switch to 7.1 as well.
  - [ ] Should we use HTTPlug or similar for doing curl requests in all handlers? That introduces a dependency which I honestly don't know whether it's needed as we haven't had anyone complain about the curl requirement, and our curl usage is so simplistic I doubt it's really a big benefit
  - [ ] https://github.com/Seldaek/monolog/issues/903 needs to be clarified, please let's do that over there.
  - [ ] Whatever is left in [the milestone](https://github.com/Seldaek/monolog/milestone/1) needs to be looked at. I tried to leave comments where I had anything to say.
  - [ ] Changelog needs to be updated.. not a fun exercise but I guess I'll get to it some time.

My overall goal with 2.0 is to get it stable soon so that we can also move symfony/monolog-bundle to use it and Symfony 4.2 (hopefully) can target it as it's also requiring PHP 7.1. Obviously due to the big jump Monolog 1.x will have to be maintained for a while, but the amount of bugfixes is fairly low at this point, as we can see I could vanish for a year here and almost nobody noticed ;) 

In the longer run, I don't know who would make sense to bring on board with access to the repo.. I guess it would be a good thing to have one or two more people in there, but for now most of the above can be done without commit access anyway so please don't let that stop you if you wanna help.

**Comment by helhum** [comment]
I'm going to review #1117 as soon as possible. I'll be off to a conference this week, so could be it takes until next week.

**Comment by RGustBardon** [comment]
@helhum: Thank you very much!

**Comment by helhum** [comment]
Looked into #1117. Looks good so far. I've added some general questions to the ticket though.

Meanwhile #1174 appeared, which I have taken a look into. Looks pretty straightforward to merge and include in next release.

**Comment by Seldaek** [comment]
Closing here as good progress has been made.. and the 2.0 milestone has all that's left to be done https://github.com/Seldaek/monolog/milestone/1
