### ISSUE TITLE
2.0 Code cleanups / tasks

### ISSUE THREAD

**Issue by Seldaek** [Seldaek/monolog#197]
- [x] ~~Clean up arg orders of handlers that have had added args pushed at the end (after bubbling etc), maybe group them in an $options array or parameter objects? Needs RFC. Check #801 too about fluent setters~~
- [x] add scalar hints and return type hints where relevant ("only" handlers left to go through)
- [x] ~~figure out how to handle network timeouts globally somehow, see #733~~
- [x] Add a close() method on the Logger to close all its handlers? What about resetting FingersCrossedHandler?
- [x] Define which php version should be supported (=> 7.1)
- [x] Add a timezone arg to Logger instead of the static timezone?
- [x] Turn static::getLevelName into static::
- [x] Set Monolog\Logger::API = 2 to allow users to adjust
- [x] Remove non PSR-3 methods to add record
- [x] Remove processor/formatter setters and getters from the HandlerInterface
- [x] Remove logstash V0 support or at least make V1 default
- [x] Remove legacy GELF handler support, c.f. #326
- [x] Remove datetime TODO in loggly handler
- [x] Move `Monolog\TestCase` to src/, see https://github.com/Seldaek/monolog/pull/356#issuecomment-40899938
- [x] ~~Split handlers w/ dependencies into packages i.e. http://php-and-symfony.matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/~~
- [x] ~~Change Logger constants to have RFC values (https://github.com/php-fig/log/issues/8)~~
- [x] Remove substr TODO in AmqpHandler
- [x] Remove default handler (`$this->pushHandler(new StreamHandler('php://stderr', static::DEBUG));`) from Monolog\Logger
- [x] ~~Consider adding a public method (send or write or so) on handlers to make reusing them out of monolog easier, c.f.~~ https://github.com/Seldaek/monolog/commit/f3b61cf48af2c0730f149ae48f930e12a3bec1f2#commitcomment-8237858
- [x] Consider using MongoDBFormatter as default in MongoDBHandler
- [x] Drop support for outdated mongo exts in MongoDBHandler
- [x] Remove BC __get() in SwiftMailerHandler
- [x] Update HipChat to API v2 using 01549ec4d05e2d3f33227531d9fc9454d5ef6049 and `room_id` and `from` in buildContent (+ `nickname` everywhere) should be removed. See if we can't detect the token format and warn users using a v1 token.
- [x] Check all PHP_VERSION and version_compare checks for relevance
- [x] LineFormatter when showing stack traces should show new lines on new lines, and not the exception as part of the context that gets inlined into json => #752
- [x] Consider removing useless PHP docs if the scalar + return type hints give enough info
- [x] Disable microseconds timestamps by default?

php7 ideas:
- [x] treat Error-class exceptions in a special way as they are replacing E_COMPILE_ERROR and such from defaultErrorLevelMap
- [x] ~~possibly remove ErrorHandler::registerFatalHandler if this is not needed anymore~~
- [x] enable strict mode everywhere?

~~those items have been abandoned~~

**Comment by ChristianRiesen** [comment]
Just a small side note on the naming FingersCrossed: The concept is close to tripping a fuse, a common pattern in flood avoidance code. BufferedFuse? FuseTripping? I'm not saying these are good, but maybe will inspire someone for a better one. Good naming will save a lot of time for many I think, just judging from how many already said here that they essentially started implementing it on their own as well.

**Comment by ZergMark** [comment]
"Drop support for outdated mongo exts in MongoDBHandler" can be marked as done via #307.

Very Minor PHP 7 Ideas:
1. Return type declarations
2. Group use declarations

**Comment by rpkamp** [comment]
Why was "Split handlers w/ dependencies into packages" crossed out? It seems like a good idea to me. At the moment if you want to develop for monolog and run all the tests to make sure you haven't broken anything you need to install a _lot_ of dependencies, one of which I don't even have access to at all (Zend Server). If parts that need additional dependencies were to be split off of the main repository it would make developing a lot easier imo.

**Comment by stof** [comment]
@ZergMark return types are used in several places already.

**Comment by moderndeveloperllc** [comment]
@stof In my defense, there were quite a bit fewer uses back in March (@ZergMark is an older business account). :-)

**Comment by elazar** [comment]
Potentially related to this and #903: a number of handlers are using the curl extension directly for interacting with third-party services:

* Loggly
* IFTTT
* Slackbot
* SlackWebhook
* Mandrill
* Cube
* SendGrid

Support for environments without the curl extension could be possible by refactoring these handlers to use Guzzle instead.

**Comment by rpkamp** [comment]
Instead of going for Guzzle I would consider [HTTPlug][httplug] instead so people can provide their own implementation.

[httplug]: https://github.com/php-http/httplug

**Comment by hkdobrev** [comment]
I'd like to chime in on the old topic of `FingersCrossedHandler`. Sentry has a concept exactly for that and they call it "breadcrumbs" - what notable events you went through prior to the exception. I'd suggest `BreadcrumbHandler` as I think most people would get it right away and it fits the prior art of Sentry.

**Comment by filips123** [comment]
What will be different between Monolog 1 and 2? Will existing code still work?

**Comment by staabm** [comment]
The point of a new major version is mostly that it will break „some“ things, hopefully not too much

**Comment by Seldaek** [comment]
Yeah the goal is to keep things working for end users apart from the configuration of the logger (which is mostly abstracted in other places/frameworks anyway). You can see https://github.com/Seldaek/monolog/blob/master/UPGRADE.md for the current listed BC breaks, the first two kinda affect regular usage.

**Comment by filips123** [comment]
What will be minimal PHP version? Bacause  some systems like Ubuntu 14.04 and 16.04 don't have latest PHP version (7.2) in repositories.

**Comment by stof** [comment]
@filips123 For now, it requires PHP 7.1+

**Comment by stof** [comment]
and if you still need to support PHP 5.5, the solution is simple: keep using Monolog 1.x. It won't magically stop working the day 2.0 is released.
